#ruby '2.0.0'
source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'foreman'
gem 'haml-rails'
gem 'rest-client'
#gem 'rails_12factor'
gem 'activeresource', require: 'active_resource'
gem 'rack-contrib'
gem 'jquery-rails'
gem 'turbolinks'
gem 'therubyracer',  platforms: :ruby
#gem 'paperclip', '~> 4.2'
#gem 'nested_form'
gem 'httmultiparty'
gem 'sdoc', '~> 0.4.0',          group: :doc
#gem 'thin'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'virtus'
gem 'faraday'
gem 'faraday_middleware'
gem 'newrelic_rpm'
gem 'boxr'
gem 'puma'
gem 'bootsy'

#group :development do
#  gem 'pry-byebug'
#  gem 'sextant'
#  gem 'awesome_print'
#end
